# Use NodeJS base image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy dependency files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all source code
COPY . .

# Expose Next.js default port
EXPOSE 3000

# Run frontend server
CMD ["npm", "run", "dev"]
